services:
  app:
    depends_on: 
      - db
    build: .
    ports:
      - 8000:8000
    networks:
      - shorty-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/urls?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_SHOW-SQL=true

  db:
    ports:
      - 3306:3306
    image: mysql:latest
    networks:
      - shorty-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
networks:
  shorty-network:
    driver: bridge